### ISSUE TITLE
Traces conducted using x-cloud-trace-context not correctly recording parent span

### ISSUE THREAD

**Issue by dzou** [openzipkin/zipkin-gcp#106]
I have been playing around with the [Spring GCP Trace Sample Application](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample) which lets you try using the x-cloud-trace-context header to trace requests.

I noticed something odd when I do the following HTTP requests on the app:

- When I add a header for tracing i.e. `curl --header "x-cloud-trace-context: xxxxxx/123;o=1" localhost:8080`, the value `123` is set as the parentSpanId of one of the spans, and none of the recorded spans are "root-level" (i.e. without a parentSpanId). None of the spans are registered as "123" which suggests to me that it was never successfully recorded as a root-level span.

- When I do a normal `curl localhost:8080`, all the spans are recorded correctly (I assume the app must be defaulting to b3 headers). One of the recorded spans in the collection is clearly the "root span" with a missing parentSpanId.

Is there some special logic which goes into what gets created as the root span of a trace that we are missing? Or is that logic outside the control of these libraries?

cc/ @meltsufin

**Comment by adriancole** [comment]
stackdriver assumes that spans are different client to server. B3
supports sending the ID you want to use (sharing spans) by default,
where stackdriver propagation says "use this as your parent" make
sense?

https://github.com/openzipkin/b3-propagation#why-is-parentspanid-propagated

always creating child has benefits in so far as accidental mid-tier
retries don't screw up trace hierarchy. It does complicate choosing
the ID of the root span. In amazon X-Ray propagation, for example,
passing the span ID is optional. So, when only a trace ID is sent,
brave will create a new root span. Make sense?

-A

**Comment by dzou** [comment]
Ah ok, that makes sense. So based on what you are saying, I think this means our Propagation impl is not quite correct as we are not handling the case when only TraceId is sent. Specifically from TraceContextOrSamplingFlags:

```
Those implementing Propagation should use the following advice:
- If you have the trace and span ID, use create(TraceContext).
- If you have only a trace ID, use create(TraceIdContext)
- Otherwise, use create(SamplingFlags)
```

In stackdriver trace, [you can set your span id to 0 like this](https://cloud.google.com/trace/docs/troubleshooting): `105445aa7843bc8bf206b120001000/0;o=1` where the values are formatted as `TRACE_ID/SPAN_ID;o=1`. So in the context of Stackdriver, `0` basically means no spanId is provided and that you want a new root span.

So I think we should change our impl so that if the passed in spanId == 0, we should create a `TraceIdContext` rather than `TraceContext`.
