### ISSUE TITLE
Stackdriver Trace V2 API translation

### ISSUE THREAD

**Issue by anuraaga** [openzipkin/zipkin-gcp#111]
I'm thinking of working on converting to Stackdriver Trace V2 (https://cloud.google.com/trace/docs/reference/v2/rpc/google.devtools.cloudtrace.v2#google.devtools.cloudtrace.v2.TraceService)

One thought I have, is it worth keeping the current V1? I'm not sure if there's a use case for it since GCP itself supports both V1 and V2 let me know if you have any thoughts.

**Comment by anuraaga** [comment]
Also should add the main reason I want to get to V2 now is support for annotations, we currently lose annotations when translating to V1.

**Comment by adriancole** [comment]
unless there is a feature lost v1 to v2 seems v2 only is a good idea.

**Comment by anuraaga** [comment]
Found a first difference, there is no `Kind` in the API. opencensus does this weird name mangling (add `Recv.` and `Send.` prefix to span name)

https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java

https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/trace_proto.go#L55

Our go code happens to manually add `/span/kind` label, I actually don't remember adding that but it may have been inspired by opentracing or something.

FWIW, the Kind in the V1 API doesn't seem to be used anywhere - I don't see client / server mentioned on any of the traces exported through the current translator. I'm not surprised since if V2 doesn't have it, whatever reads V1 on their end must just be dropping it.

Should we follow the opencensus convention? Make it flaggable? I'm also curious whether their UI will still allow searching by just the span name if those prefixes are attached.

**Comment by adriancole** [comment]
maybe @mtwo or someone else knows when stackdriver will have kind again?

**Comment by anuraaga** [comment]
Also one question - since this isn't GA yet is it ok to make API changes? The fact that spans require project ID now (since the concept of Trace is gone completely) means I have to move projectId from `StackdriverSender` to `StackdriverEncoder`, the latter of which will stop being an enum.

**Comment by anuraaga** [comment]
Well maybe not - I guess I can just leave the calculation of the span's name to the end, false alarm.

**Comment by adriancole** [comment]
very few people will be making custom use of the encoder. generally we dont
make api warranties on pre 1.0 libraries

**Comment by anuraaga** [comment]
Yeah have a PR which is mostly done, just haven't gotten a chance to finish the last mile but think I'll get to it early next week.
