### ISSUE TITLE
0.10.0 Spans not sending to stackdriver

### ISSUE THREAD

**Issue by neoshrew** [openzipkin/zipkin-gcp#115]
Currently I have a `openzipkin/zipkin-gcp:0.10.0` container deployed in a GKE cluster, I can successfully sent traces to it and if I enable stackdriver translation DEBUG logging it spits out is below. 

If I use `0.9.0` or `0.8.0` it works as expected, and as far as I can tell there aren't any extra IAM permissions required for `v2` so I don't believe it to be an issue with the service account.

When I check the metrics for the Stackdriver Trace API in GCP it doesn't show any traffic to the `v2` endpoints. I am not sure where to begin to look to diagnose why the metrics aren't being sent to stackdriver.

```
2019-02-13 17:00:30.943 DEBUG 7 --- [   XNIO-1 I/O-2] z.t.s.SpanTranslator                     : >> translating zipkin span: {"traceId":"1e4d6916a743d9e7","id":"1e4d6916a743d9e7","kind":"SERVER","name":"get","timestamp":1550077229833000,"duration":220587,"localEndpoint":{"serviceName":"koa-server","ipv4":"192.168.113.219"},"tags":{"http.method":"GET","http.status_code":"200","http.url":"http://localhost:3000/uk/?this_is_a_test"}}
2019-02-13 17:00:30.944 DEBUG 7 --- [   XNIO-1 I/O-2] z.t.s.SpanTranslator                     : << translated to stackdriver span: span_id: "1e4d6916a743d9e7"
display_name {
  value: "get"
}
start_time {
  seconds: 1550077229
  nanos: 833000000
}
end_time {
  seconds: 1550077230
  nanos: 53587000
}
attributes {
  attribute_map {
    key: "/kind"
    value {
      string_value {
        value: "server"
      }
    }
  }
  attribute_map {
    key: "/http/method"
    value {
      string_value {
        value: "GET"
      }
    }
  }
  attribute_map {
    key: "/http/status_code"
    value {
      string_value {
        value: "200"
      }
    }
  }
  attribute_map {
    key: "/http/url"
    value {
      string_value {
        value: "http://localhost:3000/uk/?this_is_a_test"
      }
    }
  }
  attribute_map {
    key: "endpoint.ipv4"
    value {
      string_value {
        value: "192.168.113.219"
      }
    }
  }
  attribute_map {
    key: "/component"
    value {
      string_value {
        value: "koa-server"
      }
    }
  }
  attribute_map {
    key: "/agent"
    value {
      string_value {
        value: "zipkin-java"
      }
    }
  }
}
```

**Comment by adriancole** [comment]
maybe best to use gitter? someone else was able to get their things working on gcp last night there https://gitter.im/openzipkin/zipkin

we define issues as changes to code or docs

**Comment by adriancole** [comment]
similar to #114 also

**Comment by adriancole** [comment]
fyi @mtwo we are getting spurious complaints about v2 api. here's one

**Comment by adriancole** [comment]
@neoshrew I have cut 0.10.1 just in case latest versions of things fix this. can you please try just in case?

**Comment by adriancole** [comment]
here is one reason a version update could work. If you are using the docker image, the patch updates the ssl library needed for stackdriver to work. this could explain spurious behavior with docker and not if someone isn't using docker.

https://github.com/openzipkin/docker-zipkin-gcp/commit/360a8ec6d464a10e6d2d645f6dab2bccfc7e0763#diff-3254677a7917c6c01f55212f86c57fbfR24
