### ISSUE TITLE
Should Brave version be upgraded to 5.7.0?

### ISSUE THREAD

**Issue by elefeint** [openzipkin/zipkin-gcp#146]
Should this version come from the BOM? Was it hardcoded here just because `spring-cloud-gcp` could not upgrade?

https://github.com/openzipkin/zipkin-gcp/blob/c164b9ca4d0fca9a1d6bf1be2738147fb632a073/pom.xml#L51

**Comment by adriancole** [comment]
bom'ing it seems right (deleting the other zipkin versions)

note: sleuth 2.1.3, which is imminent, uses that version

**Comment by elefeint** [comment]
I am going to close this issue, as the original issue was very `spring-cloud-gcp` specific; I don't think a discrepancy between `zipkin-gcp` and `spring-cloud-sleuth` versions would affect anyone else.
