### ISSUE TITLE
Unable to release 0.14.1 to maven central

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-gcp#156]
I don't know how many know about this stuff... most is documented in [RELEASE.md], anyway the automation is currently not working because the last step to sync to maven central fails. This results in the ability to see version 0.14.1 or build the docker image from it (currently our docker images are built from maven central, not bintray, though we can change that).

I verified this isn't a bintray problem in their api, rather something in sonatype itself, or something in the packaging is triggering a bug in sonatype. For example, I [logged in](https://oss.sonatype.org/#stagingRepositories) to sonatype with access granted [here](https://issues.sonatype.org/browse/OSSRH-16669). Then I validated manually by looking at the files and then clicked close.

![Screenshot 2019-09-27 at 10 17 52 AM](https://user-images.githubusercontent.com/64215/65737326-b7bf3a80-e110-11e9-932b-210082a53f52.png)

The sonatype UI errored out like so:
 
![Screenshot 2019-09-27 at 10 19 59 AM](https://user-images.githubusercontent.com/64215/65737334-c148a280-e110-11e9-9904-6ee2cc05b5f1.png)

This might be a temporary glitch, but it could also be a problem in what's being uploaded by bintray. What's uploaded is our content plus signatures the bintray service uses. Noticing a couple abandoned opentracing repos (I still have sonatype access to that), it may be a general problem.

If it ends up not a general problem, signing locally and uploading should work
https://github.com/openzipkin/zipkin-gcp/blob/master/RELEASE.md#manually-releasing

I'm cc'ing @openzipkin/devops-tooling as we I don't think cover how to diagnose bad releases in this sort of depth, yet. It is somewhat common that bintray fails so might be helpful to add more content to RELEASE.md for break-glass weather

**Comment by adriancole** [comment]
cc also @anuraaga eventhough I know you don't use this repo anymore you are a routine contributor so should know how to dive into the problems, if you haven't already encountered similar in other projects.

**Comment by adriancole** [comment]
trying "skip bintray" approach signing GPG with my local key as opposed to bintray's dummy one. This is following same steps as here https://github.com/openzipkin/zipkin-aws/pull/137

**Comment by adriancole** [comment]
It is so slow it is almost hanging.. Although sonatype is not reporting any problems, I think the problem might be on sonatype side. Someone can use jitpack or jcenter release if they need the release now.

**Comment by devinsba** [comment]
I wanted to chime in real quick, I saw that the Jackson team had issues with their release the other night due to sonatype failures. They had a release that they couldn't get to sync to central so it seems like the same failure

https://groups.google.com/forum/#!topic/jackson-user/RtPWxXsJ7cA

**Comment by adriancole** [comment]
https://twitter.com/sonatype_ops/status/1177605285122232323
