### ISSUE TITLE
Upgrade brave and fix incompatibility

### ISSUE THREAD

**Issue by elefeint** [openzipkin/zipkin-gcp#175]
Upgrade to `io.zipkin.brave:brave:5.12.3`.
`HexCodec` got moved into a subpackage in openzipkin/brave#1193; this requires a change in `zipkin-gcp`.

**Comment by adriancole** [comment]
I'll look for whatever is using that internal type and shade it!

**Comment by elefeint** [comment]
Excellent, between short term in #176 and long term shading fix in #174, this is well and truly resolved. Closing issue.
