### ISSUE TITLE
avoid io.netty.util.internal.PlatformDependent

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin-gcp#177]
ZipkinStackdriverStorageModule is using the only internal type not yet shaded.

io.netty.util.internal.PlatformDependent

As internally, this checks for android which won't be the case in spring boot. then it seems to just parse a property.. possibly we can avoid shading complexity and just inline a function? Also, I'm not even sure spring boot can run on java 7 anymore?

cc @spencergibb

**Comment by spencergibb** [comment]
Spring boot 2.0 requires Java 8. The 1.x line is end of life

**Comment by adriancole** [comment]
whoops.. this is looking for <= 8 sorry.. I guess still need some variant of the check to see if it is 1.8 or not

**Comment by adriancole** [comment]
I feel like just looking at property "java.specification.version" for "1.8" is enough

**Comment by codefromthecrypt** [comment]
latest code this is completely irrelvant as floor JRE 17
