### ISSUE TITLE
Pub/Sub messaging instrumentation

### ISSUE THREAD

**Issue by meltsufin** [openzipkin/zipkin-gcp#190]
The original request is here: https://github.com/spring-cloud/spring-cloud-gcp/issues/2073, but I think it belongs better in this repo. As I started working on it, I realized that we can implement the instrumentation without any dependency on Spring Cloud GCP, which would enable it to be useful in wider contexts.

**Feature:**
Implement Brave instrumentation for Pub/Sub client library, similar to [Kafka](https://github.com/openzipkin/brave/tree/master/instrumentation/kafka-clients) or [Spring Rabbit](https://github.com/openzipkin/brave/tree/master/instrumentation/spring-rabbit).

**Rational**
Although this can be partially achieved with Spring Integration, it doesn't work when using the [`PubSubTemplate`](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/core/PubSubTemplate.java) directly. If we instrument the `Publisher`, `Subscriber`, and `SubscriberStub.pullCallable()`, we can provide general Brave messaging instrumentation for Pub/Sub client library, which would also allow us to provide instrumentation for `PubSubTemplate` as well.

**Example Scenario**
This would enable tracing for applications that use Pub/Sub to exchange messages across microservices.

**Prior Art**
 * [Kafka instrumentation](https://github.com/openzipkin/brave/tree/master/instrumentation/kafka-clients)
 * [Spring Rabbit instrumentation](https://github.com/openzipkin/brave/tree/master/instrumentation/spring-rabbit)
 * [AWS SQS instrumentation](https://github.com/openzipkin/zipkin-aws/tree/master/brave/instrumentation-aws-java-sdk-sqs)
   * Interestingly this implementation only supports the producer side. I'm not sure why.

@adriancole I'm happy  to work on contributing this. Do you have any thoughts on the approach and whether it belongs in this repo?

**Comment by adriancole** [comment]
seems good for here, Mik. When using anything for a model, Kafka (or JMS) are the better ones to look at as they've had more eyes and experience. spring-rabbit is a bit weird as it relies on JMS. The AWS instrumentation are a mixed bag.

**Comment by dinvlad** [comment]
Any updates on this @meltsufin or anyone else? Not sure I understand if PubSub tracing is fully supported or not now with Cloud Trace and Spring Stream binders..

**Comment by elefeint** [comment]
This was done in Spring Cloud GCP > 2.0.6, see [docs here](https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.7/reference/html/index.html#pubsub-trace-instrumentation-experimental).

We are no longer planning to port functionality into this repo, so I'll close the issue.

**Comment by elefeint** [comment]
Oh, and Spring Integration / Spring Cloud Stream tracing was supported even prior to this.

**Comment by dinvlad** [comment]
OK, thanks for clarifying!
