### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by zmknox** [openzipkin/zipkin-gcp#198]
## Describe the Bug
Some links out to examples on how to utilize this project seem to go to files that no longer exist in this project.

Such as here: https://github.com/openzipkin/zipkin-gcp#example-integrating-stackdriver-storage
where the example links to https://github.com/openzipkin/zipkin-gcp/blob/master/autoconfigure/storage-stackdriver#quick-start , which doesn't exist.

And here: https://github.com/openzipkin/zipkin-gcp/tree/master/docker#stackdriver
which links to https://github.com/openzipkin/zipkin-gcp/blob/master/module/storage-stackdriver#configuration , which doesn't exist.

**Comment by yuriatgoogle** [comment]
+1, I was looking for instructions on how to configure Zipkin to send traces to Cloud Trace and hit the same issues.

**Comment by jcchavezs** [comment]
Would you open a PR with such fixes?

**Comment by codefromthecrypt** [comment]
the easiest way is docker as it is pre-assembled https://github.com/openzipkin/zipkin-gcp/tree/master/docker#running
next is to assemble your own https://github.com/openzipkin/zipkin-gcp/tree/master/docker#running

I'll fix the README in a sec

**Comment by codefromthecrypt** [comment]
@zmknox @yuriatgoogle sorry no one took any action on this. https://github.com/openzipkin/zipkin-gcp/pull/212 should both fix the links and make the build break if it happens again.
