### ISSUE TITLE
Efficiency over paid network links

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-gcp#37]
Somewhat relating to #36, zipkin has users in AWS that are interested in stackdriver integration. The question of cost came from a twitter conversation (translated by @shakuzen)

I think there's a few things we could do to limit network impact:
* use zipkin-reporter-java's [AsyncReporter](https://github.com/openzipkin/zipkin-reporter-java/blob/master/core/src/main/java/zipkin/reporter/AsyncReporter.java) or another means to bundle patch requests so that people can try not to run over stackdriver's quota for external requests
  * this has a secondary plus, as making a StackDriverSender allows apps to embed stackdriver support without running an external process. For example, sleuth could natively support stackdriver this way.
* explore compression. trace data is mostly strings (even if in protos) and compresses really well, which can limit paid egress from clouds like amazon.

**Comment by elefeint** [comment]
@adriancole Sorry for the noise today -- we've been going over the team's issues. `AsyncReporter` bundles messages as far as I know, so I was wondering whether this issue is obsolete or still relevant?

**Comment by adriancole** [comment]
Ah this is about the proxy (zipkin-gcp image). We still don't do anything like this, but as it was speculative on my part will close it.
