### ISSUE TITLE
No more monkey business... at least in senders!

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-gcp#67]
Hi, all. This all applies to senders.

I would like to remove the id rewriting and move all data mapping to be independent of span encoding. Here's why:

## no more ID rewriting
While seemingly a good idea, id rewriting is extremely fragile and won't work in a mixed environment. For example, it works by a consistent hash function. If you have the ability to deploy this consistent hash function, then you have the ability to affect the code. If you can do that, just turn off "supportsJoin" function or ask the library to do that. Similarly, but less impactfully, just set "traceId128bit" to true. I know these features exist in at least go, java and php

## no more span name and tag rewriting
If you can parse the tags, why not set them to what you want in the first place? A decorating SpanReporter could be used in worst case, but better to push for libraries to allow customization of this.

If the above are removed from the critical path, I'm quite certain we can shrink this benchmark considerably:

StackdriverEncoderBenchmarks.sizeInBytesClientSpan_json_stackdriver_proto3  avgt   15  1.135 ± 0.039  us/op
StackdriverEncoderBenchmarks.sizeInBytesClientSpan_json_zipkin_json         avgt   15  0.119 ± 0.005  us/op

The "sizeInBytes" feature is very slow in proto due to conversion and also inherit inefficiencies.

So.,. what say you?

**Comment by anuraaga** [comment]
Yeah when I saw the ID rewriting logic while migrating to new v2 API, I was a bit confused since I didn't see a need for it. +1 to dropping it

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-gcp/pull/80
