### ISSUE TITLE
Simple setup, healthcheck failure

### ISSUE THREAD

**Issue by zachdaniel** [openzipkin/zipkin-gcp#75]
I followed the guide here: https://cloud.google.com/trace/docs/zipkin And used the startup script option for GCP. I've now sshd and I'm port forwarding locally for testing. However, when I check the healthcheck I get this:
```
{"status":"UP","zipkin":{"status":"UNKNOWN"},"diskSpace":{"status":"UP","total":10499674112,"free":8691965952,"threshold":10485760}}
```

Any ideas?
Thanks :D

**Comment by zachdaniel** [comment]
I have the same effect if run as a daemon set in my kubernetes cluster.

**Comment by zachdaniel** [comment]
I'm also using an erlang open tracing client that sends things to a zipkin instance, and (the documentation on google is really just horrendous around all of this) it looks like perhaps I'm missing an important piece here?

**Comment by zachdaniel** [comment]
I should also add that when I hook up to a normal instance of a zipkin server that I see trace data. Its only using this that I don't see trace data in stackdriver, and I'm not sure the best way to go about debugging it.

**Comment by adriancole** [comment]
the old image is replaced by the content here. does advice in https://github.com/openzipkin/zipkin-gcp/issues/74 help? You should be running the zipkin-gcp image basically

**Comment by zachdaniel** [comment]
@adriancole trying it out now, I misread that issue originally, but I see now how it could be helpful!

**Comment by zachdaniel** [comment]
@adriancole I'm a bit confused. I'm not supposed to run both am I?

**Comment by adriancole** [comment]
I reworded that issue.. right zipkin-gcp replaces the old image. You don't
need to and shouldn't run both.

**Comment by zachdaniel** [comment]
I've got traces going into a local zipkin server, are there special rules about the tags I need, or about what values certain tags can have?

**Comment by adriancole** [comment]
I think I need to merge https://github.com/openzipkin/zipkin-gcp/pull/73 what do you think?

**Comment by zachdaniel** [comment]
I can't say with little experience, but merge away and I'll try it out!

**Comment by jsw** [comment]
@zachdaniel I found `/metrics` helpful in verifying that it's sending traces to Stackdriver. Look for `counter.zipkin_storage.stackdriver.sent`. Also make sure your cluster has the `trace.append` oauth scope via `gcloud container clusters describe ... | grep trace.append`

**Comment by zachdaniel** [comment]
@jsw interesting, I don't see that key at all. I *do* see a bunch of spans as "dropped", so perhaps there is a problem with my spans?

**Comment by adriancole** [comment]
I'm releasing 0.3.2 which hopefully will become a docker image within an
hour.

meanwhile feel free to use https://gitter.im/openzipkin/zipkin for
exploratory troubleshooting

**Comment by jsw** [comment]
@adriancole It looks like the `counter.zipkin_storage.stackdriver.sent` metric is only present in the gcr image? Wondering if it got lost in the zipkin-gcp image.

**Comment by adriancole** [comment]
That is not a normal metric. The drop metric covers lost for any reason. In
other words if you are not seeing drop metrics the server accepted the
spans. That doesnt necessarily mean they processed properly after getting
to goog though.

**Comment by zachdaniel** [comment]
```
{  
   "mem":611627,
   "mem.free":300139,
   "processors":2,
   "instance.uptime":3305466,
   "uptime":3317785,
   "systemload.average":0.19,
   "heap.committed":540160,
   "heap.init":120832,
   "heap.used":240020,
   "heap":1703936,
   "nonheap.committed":73696,
   "nonheap.init":2496,
   "nonheap.used":71468,
   "nonheap":0,
   "threads.peak":19,
   "threads.daemon":12,
   "threads.totalStarted":29,
   "threads":19,
   "classes":9687,
   "classes.loaded":9687,
   "classes.unloaded":0,
   "gc.ps_scavenge.count":13,
   "gc.ps_scavenge.time":244,
   "gc.ps_marksweep.count":2,
   "gc.ps_marksweep.time":151,
   "gauge.zipkin_collector.message_spans.http":5.0,
   "gauge.zipkin_collector.message_bytes.http":4500.0,
   "counter.zipkin_collector.messages.http":7,
   "counter.zipkin_collector.spans_dropped.http":165,
   "counter.zipkin_collector.bytes.http":152759,
   "counter.zipkin_collector.spans.http":165,
   "counter.status.200.health":1,
   "gauge.response.star-star":21.0,
   "gauge.response.health":59.0,
   "counter.status.404.star-star":1
}```

**Comment by adriancole** [comment]
Yep so if you set debug logging you can see maybe the reason. Look at the
README for the args

**Comment by adriancole** [comment]
To get all do

JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG

**Comment by adriancole** [comment]
Reason it isnt logging failures by default is if something in your net has
bad impl it would fill up disks. The counters tell yoi something is
failing..

**Comment by zachdaniel** [comment]
@adriancole yeah, that makes sense! Thanks I'll try it out!

**Comment by zachdaniel** [comment]
🤦‍♂️ The trace API was not enabled.

**Comment by zachdaniel** [comment]
Now I'm getting `PERMISSION_DENIED: The caller does not have permission`, but I checked and those oauth scopes are granted on the cluster.

**Comment by zachdaniel** [comment]
I got everything worked out :D It was an issue w/ the service account's permissions, the oauth scope on the cluster was not enough, I also needed properly configure the service account to have write access to the Trace API

**Comment by zachdaniel** [comment]
I got everything worked out :D It was an issue w/ the service account's permissions, the oauth scope on the cluster was not enough, I also needed properly configure the service account to have write access to the Trace API
