### ISSUE TITLE
[Question] How do we set different attributes for the UI

### ISSUE THREAD

**Issue by ankurcha** [openzipkin/zipkin-gcp#9]
Are there any ways to set the following attributes that would show up correctly in the trace console:

* Service
* Version
* Http method

Especially for grpc services.

**Comment by kevinmdavis** [comment]
The "/http/method" label corresponds with that field in the console. I'll investigate why this isn't showing up.

We don't currently have a generic way to set the Service and Version (those attributes correspond with the AppEngine Service and Version). I'll see if this is something we can support outside of AppEngine.

**Comment by zachdaniel** [comment]
I also need to figure out what labels and/or tags I could use to set the service and version. I'm using a different client, so right now service appears to just not be set at all in stackdriver, which is a problem :)

**Comment by jsw** [comment]
Is there a documented mapping between zipkin fields and stackdriver fields?

**Comment by zachdaniel** [comment]
@jsw I looked all around, but I could not find it :/

**Comment by zachdaniel** [comment]
There is a list of predefined labels here, but its not quite what we're looking for
https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#Trace

**Comment by adriancole** [comment]
census has started inventorying these. there might be some mapping work
still needed

https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/HTTP.md#attributes

**Comment by zachdaniel** [comment]
I still haven't figured out how to set the service (or if any tag suffices to set the service) using the client I'm using. Any tips there?

**Comment by adriancole** [comment]
In zipkin format the service name isnt a tag, it is
span.localEndpoint.serviceName

"localEndpoint": {
  "serviceName": "tweetiebird"
}

Do you have a trace that doesnt work and a screenshot of what you want to
see? For example of using osx preview, you can add an arrow to a screenshot.

**Comment by nicodeur** [comment]
Hi, I have found the solution to  show up correctly `Service`, `version` and `Http method` to the GCP Trace console.

You have to set this tags/labels on you zipkin span : 
```
"g.co/gae/app/module" : servicename
"g.co/gae/app/version" : servicename+":"+version+"."+version
```

I haven't found documentation about this subject, but it's work fine ! This is this documentation about Trace filter who help me : https://cloud.google.com/trace/docs/trace-filters

**Comment by saturnism** [comment]
Found the trace labels list. But I don't think we have a mapping btwn the Sleuth/brave labels w/ Cloud Trace:

https://cloud.google.com/trace/docs/trace-labels

**Comment by adriancole** [comment]
Seems a good README update for someone to help with. reverse engineer the current mappings, then on PR update that!
